### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [haugom/jamming#4]
Awesome job overall. Probably the best Jammming project I've seen. It's cool that you went above and beyond and added some extra functionality like the spinner. Also, nice work adding the ability to search on `Enter`. All in all, great job on this project. You clearly understand React and you should do a great job in the field.

**Comment by haugom** [comment]
Hi

Thanks for the kind review. I'm glad you liked it. I got carried away when I saw how to create react components and make react do all the rendering work.
